version: '3.3'

services:
  db:
    image: postgres:14
    container_name: db_postgres
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    env_file:
      - "./config/db.env"
    networks:
      - backend_pizzaria
    ports:
      - "5432:5432"

  api:
    depends_on:
      - db
    image: node:16.15.1
    container_name: api_pizzaria
    working_dir: /dist
    command: bash -c "npm install && npm run npx && npm run debug"
    volumes:
      - ./dist/:/dist/
      - ./package.json:/package.json
      - ./pnpm-lock.yaml:/pnpm-lock.yaml
      - ./prisma:/prisma
      - ./.env:/.env
      - ./tsconfig.json:/tsconfig.json
    restart: always
    networks:
      - backend_pizzaria
    ports:
      - "3000:3000"
      #- "9222:9222"

volumes:
  db_data: {}
networks:
  backend_pizzaria:
    driver: bridge
